apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: youtube-music-sync-secrets
  namespace: youtube-music-sync
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: youtube-music-sync-secrets
    creationPolicy: Owner
  data:
    - secretKey: YT_DLP_PATH
      remoteRef:
        key: youtube-music-sync-secrets
        property: YT_DLP_PATH
    - secretKey: FFMPEG_PATH
      remoteRef:
        key: youtube-music-sync-secrets
        property: FFMPEG_PATH