apiVersion: v1
kind: Service
metadata:
  name: youtube-music-sync-secrets
spec:
  selector:
    app: youtube-music-sync-secrets
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30082
  type: NodePort
