os_type: "linux"

ytdlp_path: "yt-dlp"

ffmpeg_path: "ffmpeg"

root_path: "/music/test"

input_method: "channel"

channel_url: "https://music.youtube.com/@KrishnarajThadesar-ud9ji"

playlist_file: "/app/playlists.txt"