resources:
  - ../../base

configMapGenerator:
  - name: app-config
    files:
      - config.yml

  - name: playlists-config
    files:
      - playlists.txt

generatorOptions:
  disableNameSuffixHash: false
