apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-music-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-music-sync
  template:
    metadata:
      labels:
        app: youtube-music-sync
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/youtube-music-sync:git-65b6218e7459dd3237d60d83d5a591d2e8bce5ad
          imagePullPolicy: IfNotPresent
          command: ["python", "main.py"]

          envFrom:
            - secretRef:
                name: youtube-music-sync-env

          volumeMounts:
            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml

            - name: playlists-config
              mountPath: /app/playlists.txt
              subPath: playlists.txt
            
            - name: music
              mountPath: /music

        # -----------------------------
        # Streamlit dashboard container
        # -----------------------------
        - name: dashboard
          image: ghcr.io/krishnarajt/youtube-music-sync:git-65b6218e7459dd3237d60d83d5a591d2e8bce5ad
          imagePullPolicy: IfNotPresent
          command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]

          envFrom:
            - secretRef:
                name: youtube-music-sync-env

          ports:
            - containerPort: 8501

          volumeMounts:
            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml

            - name: playlists-config
              mountPath: /app/playlists.txt
              subPath: playlists.txt

            - name: music
              mountPath: /music

      volumes:
        - name: app-config
          configMap:
            name: app-config

        - name: playlists-config
          configMap:
            name: playlists-config

        - name: music
          hostPath:
            path: /music
            type: Directory