apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-music-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-music-sync
  template:
    metadata:
      labels:
        app: youtube-music-sync
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/youtube-music-sync:git-ffde51c420d6fe28c91ae3a99f89b77e788f9e87
          imagePullPolicy: IfNotPresent

          command: ["streamlit", "run", "dashboard.py"]

          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: APP_CONFIG_PATH
              value: /app/config.yml
            - name: PLAYLISTS_FILE
              value: /app/playlists.txt

          volumeMounts:
            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml

            - name: playlists-config
              mountPath: /app/playlists.txt
              subPath: playlists.txt


      volumes:
        - name: app-config
          configMap:
            name: app-config

        - name: playlists-config
          configMap:
            name: playlists-config
