apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-music-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-music-sync
  template:
    metadata:
      labels:
        app: youtube-music-sync
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/youtube-music-sync:git-90a5777e1e2e51a60a00f372ca33338fb85c6e19
          imagePullPolicy: IfNotPresent
          command: ["python", "main.py"]

          envFrom:
            - secretRef:
                name: youtube-music-sync-env

          volumeMounts:
            - name: downloads
              mountPath: /downloads

            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml

            - name: playlists-config
              mountPath: /app/playlists.txt
              subPath: playlists.txt

        # -----------------------------
        # Streamlit dashboard container
        # -----------------------------
        - name: dashboard
          image: ghcr.io/krishnarajt/youtube-music-sync:git-a4d22d058dd20e224e144fc0fec90920a17eee43
          imagePullPolicy: IfNotPresent
          command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]

          envFrom:
            - secretRef:
                name: youtube-music-sync-env

          ports:
            - containerPort: 8501

          volumeMounts:
            - name: downloads
              mountPath: /downloads

            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml

            - name: playlists-config
              mountPath: /app/playlists.txt
              subPath: playlists.txt


      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: youtube-music-sync-downloads

        - name: app-config
          configMap:
            name: app-config

        - name: playlists-config
          configMap:
            name: playlists-config