apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-music-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-music-sync
  template:
    metadata:
      labels:
        app: youtube-music-sync
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/youtube-music-sync:git-a4d22d058dd20e224e144fc0fec90920a17eee43
          imagePullPolicy: IfNotPresent

          command: ["streamlit", "run", "dashboard.py"]
          
          envFrom:
            - secretRef:
                name: youtube-music-sync-env

          volumeMounts:
            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml

            - name: playlists-config
              mountPath: /app/playlists.txt
              subPath: playlists.txt


      volumes:
        - name: app-config
          configMap:
            name: app-config

        - name: playlists-config
          configMap:
            name: playlists-config
