apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: youtube-music-sync-env
  namespace: youtube-music-sync
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: youtube-music-sync-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/youtube-music-sync/youtube-music-sync/env
