apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: youtube-music-sync-env
  namespace: youtube-music-sync
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: youtube-music-sync-env
    creationPolicy: Owner
  data:
    - secretKey: PYTHONUNBUFFERED
      remoteRef:
        key: youtube-music-sync-secrets
        property: PYTHONUNBUFFERED

    - secretKey: APP_CONFIG_PATH
      remoteRef:
        key: youtube-music-sync-secrets
        property: APP_CONFIG_PATH

    - secretKey: PLAYLISTS_FILE
      remoteRef:
        key: youtube-music-sync-secrets
        property: PLAYLISTS_FILE
